# Generated by Django 4.1.6 on 2023-03-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
