# Generated by Django 4.1.6 on 2023-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
