# Generated by Django 4.1.6 on 2023-03-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_room_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='url',
            new_name='img_url',
        ),
    ]
