# Generated by Django 4.1.6 on 2023-03-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_remove_room_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img_path',
            field=models.FilePathField(null=True, path='static/reservation'),
        ),
    ]
