# Generated by Django 4.1.6 on 2023-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
