# Generated by Django 4.1.6 on 2023-03-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_rename_url_room_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img_path',
            field=models.FilePathField(default='', path='reservation/static/reservation'),
        ),
    ]
