# Generated by Django 4.1.6 on 2023-03-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_alter_room_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='img_path',
        ),
    ]
