# Generated by Django 4.1.6 on 2023-03-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_alter_room_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='img_path',
        ),
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
