# Generated by Django 4.1.6 on 2023-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
